language: php

php:
  - 5.3

before_install:
  - git clone git://github.com/sonsuzdongu/muhafiz.git /tmp/muhafiz
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - git config muhafiz.bootstrap-file /tmp/muhafiz/src/bootstrap.php
  - git config muhafiz.active-runners 'php, phpcs'
  - git config muhafiz.runners.phpcs.standard `pwd`/sonsuzdongu.xml 

script: /tmp/muhafiz/git-hooks/pre-commit
